"""
Generated by Claude -- 

LLC Management App - Python Microservices with FastAPI
Complete CRUD operations for Assets, Customers, Owners, and Expenses

# ==============================================================================
# HOW TO RUN EACH MICROSERVICE
# ==============================================================================

# Install dependencies:
pip install fastapi uvicorn sqlalchemy psycopg2-binary pyjwt pydantic[email]

# Run each service on different ports:
uvicorn main:assets_app --host 0.0.0.0 --port 8001 --reload
uvicorn main:customers_app --host 0.0.0.0 --port 8002 --reload
uvicorn main:owners_app --host 0.0.0.0 --port 8003 --reload
uvicorn main:expenses_app --host 0.0.0.0 --port 8004 --reload

# Create database tables:
Base.metadata.create_all(bind=engine)

# Access API documentation:
http://localhost:8001/docs  # Assets
http://localhost:8002/docs  # Customers
http://localhost:8003/docs  # Owners
http://localhost:8004/docs  # Expenses
"""
"""

# ==============================================================================
# SHARED DEPENDENCIES AND MODELS
# ==============================================================================

from fastapi import FastAPI, HTTPException, Depends, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, EmailStr, Field
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, sessionmaker
from datetime import datetime, timedelta
from typing import Optional, List
import jwt
import uuid

# Database setup
DATABASE_URL = "postgresql://user:password@localhost/llc_db"
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

# JWT configuration
SECRET_KEY = "your-secret-key-here"
ALGORITHM = "HS256"
security = HTTPBearer()

# Dependency for database session
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# Authentication dependency
def verify_token(credentials: HTTPAuthorizationCredentials = Depends(security)):
    try:
        token = credentials.credentials
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        return payload
    except jwt.PyJWTError:
        raise HTTPException(status_code=401, detail="Invalid authentication token")


# ==============================================================================
# 1. ASSETS MICROSERVICE
# ==============================================================================

# Database Model
class AssetDB(Base):
    __tablename__ = "assets"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    llc_id = Column(String, nullable=False, index=True)
    name = Column(String, nullable=False)
    category = Column(String, nullable=False)
    purchase_date = Column(DateTime, nullable=False)
    cost = Column(Float, nullable=False)
    current_value = Column(Float)
    depreciation_rate = Column(Float)
    description = Column(String)
    created_by = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    is_deleted = Column(Boolean, default=False)

# Pydantic Models
class AssetCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=200)
    category: str = Field(..., examples=["Equipment", "Property", "Vehicle"])
    purchase_date: datetime
    cost: float = Field(..., gt=0)
    current_value: Optional[float] = None
    depreciation_rate: Optional[float] = Field(None, ge=0, le=100)
    description: Optional[str] = None

class AssetUpdate(BaseModel):
    name: Optional[str] = None
    category: Optional[str] = None
    current_value: Optional[float] = None
    depreciation_rate: Optional[float] = None
    description: Optional[str] = None

class AssetResponse(BaseModel):
    id: str
    llc_id: str
    name: str
    category: str
    purchase_date: datetime
    cost: float
    current_value: Optional[float]
    depreciation_rate: Optional[float]
    description: Optional[str]
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

# FastAPI App
assets_app = FastAPI(title="Assets Service", version="1.0.0")

@assets_app.post("/assets", response_model=AssetResponse, status_code=status.HTTP_201_CREATED)
def create_asset(
    asset: AssetCreate,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Create a new asset"""
    db_asset = AssetDB(
        llc_id=token_data["llc_id"],
        created_by=token_data["user_id"],
        **asset.dict()
    )
    db.add(db_asset)
    db.commit()
    db.refresh(db_asset)
    return db_asset

@assets_app.get("/assets", response_model=List[AssetResponse])
def get_assets(
    skip: int = 0,
    limit: int = 100,
    category: Optional[str] = None,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Get all assets for the LLC"""
    query = db.query(AssetDB).filter(
        AssetDB.llc_id == token_data["llc_id"],
        AssetDB.is_deleted == False
    )
    if category:
        query = query.filter(AssetDB.category == category)
    return query.offset(skip).limit(limit).all()

@assets_app.get("/assets/{asset_id}", response_model=AssetResponse)
def get_asset(
    asset_id: str,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Get a specific asset by ID"""
    asset = db.query(AssetDB).filter(
        AssetDB.id == asset_id,
        AssetDB.llc_id == token_data["llc_id"],
        AssetDB.is_deleted == False
    ).first()
    if not asset:
        raise HTTPException(status_code=404, detail="Asset not found")
    return asset

@assets_app.put("/assets/{asset_id}", response_model=AssetResponse)
def update_asset(
    asset_id: str,
    asset_update: AssetUpdate,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Update an asset"""
    db_asset = db.query(AssetDB).filter(
        AssetDB.id == asset_id,
        AssetDB.llc_id == token_data["llc_id"],
        AssetDB.is_deleted == False
    ).first()
    if not db_asset:
        raise HTTPException(status_code=404, detail="Asset not found")
    
    update_data = asset_update.dict(exclude_unset=True)
    for key, value in update_data.items():
        setattr(db_asset, key, value)
    
    db.commit()
    db.refresh(db_asset)
    return db_asset

@assets_app.delete("/assets/{asset_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_asset(
    asset_id: str,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Soft delete an asset"""
    db_asset = db.query(AssetDB).filter(
        AssetDB.id == asset_id,
        AssetDB.llc_id == token_data["llc_id"],
        AssetDB.is_deleted == False
    ).first()
    if not db_asset:
        raise HTTPException(status_code=404, detail="Asset not found")
    
    db_asset.is_deleted = True
    db.commit()
    return None


# ==============================================================================
# 2. CUSTOMERS MICROSERVICE
# ==============================================================================

class CustomerDB(Base):
    __tablename__ = "customers"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    llc_id = Column(String, nullable=False, index=True)
    name = Column(String, nullable=False)
    email = Column(String, nullable=False)
    phone = Column(String)
    address = Column(String)
    status = Column(String, default="active")
    notes = Column(String)
    created_by = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    is_deleted = Column(Boolean, default=False)

class CustomerCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=200)
    email: EmailStr
    phone: Optional[str] = None
    address: Optional[str] = None
    status: str = Field(default="active", examples=["active", "inactive"])
    notes: Optional[str] = None

class CustomerUpdate(BaseModel):
    name: Optional[str] = None
    email: Optional[EmailStr] = None
    phone: Optional[str] = None
    address: Optional[str] = None
    status: Optional[str] = None
    notes: Optional[str] = None

class CustomerResponse(BaseModel):
    id: str
    llc_id: str
    name: str
    email: str
    phone: Optional[str]
    address: Optional[str]
    status: str
    notes: Optional[str]
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

customers_app = FastAPI(title="Customers Service", version="1.0.0")

@customers_app.post("/customers", response_model=CustomerResponse, status_code=status.HTTP_201_CREATED)
def create_customer(
    customer: CustomerCreate,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Create a new customer"""
    db_customer = CustomerDB(
        llc_id=token_data["llc_id"],
        created_by=token_data["user_id"],
        **customer.dict()
    )
    db.add(db_customer)
    db.commit()
    db.refresh(db_customer)
    return db_customer

@customers_app.get("/customers", response_model=List[CustomerResponse])
def get_customers(
    skip: int = 0,
    limit: int = 100,
    status: Optional[str] = None,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Get all customers for the LLC"""
    query = db.query(CustomerDB).filter(
        CustomerDB.llc_id == token_data["llc_id"],
        CustomerDB.is_deleted == False
    )
    if status:
        query = query.filter(CustomerDB.status == status)
    return query.offset(skip).limit(limit).all()

@customers_app.get("/customers/{customer_id}", response_model=CustomerResponse)
def get_customer(
    customer_id: str,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Get a specific customer by ID"""
    customer = db.query(CustomerDB).filter(
        CustomerDB.id == customer_id,
        CustomerDB.llc_id == token_data["llc_id"],
        CustomerDB.is_deleted == False
    ).first()
    if not customer:
        raise HTTPException(status_code=404, detail="Customer not found")
    return customer

@customers_app.put("/customers/{customer_id}", response_model=CustomerResponse)
def update_customer(
    customer_id: str,
    customer_update: CustomerUpdate,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Update a customer"""
    db_customer = db.query(CustomerDB).filter(
        CustomerDB.id == customer_id,
        CustomerDB.llc_id == token_data["llc_id"],
        CustomerDB.is_deleted == False
    ).first()
    if not db_customer:
        raise HTTPException(status_code=404, detail="Customer not found")
    
    update_data = customer_update.dict(exclude_unset=True)
    for key, value in update_data.items():
        setattr(db_customer, key, value)
    
    db.commit()
    db.refresh(db_customer)
    return db_customer

@customers_app.delete("/customers/{customer_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_customer(
    customer_id: str,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Soft delete a customer"""
    db_customer = db.query(CustomerDB).filter(
        CustomerDB.id == customer_id,
        CustomerDB.llc_id == token_data["llc_id"],
        CustomerDB.is_deleted == False
    ).first()
    if not db_customer:
        raise HTTPException(status_code=404, detail="Customer not found")
    
    db_customer.is_deleted = True
    db.commit()
    return None


# ==============================================================================
# 3. OWNERS MICROSERVICE
# ==============================================================================

class OwnerDB(Base):
    __tablename__ = "owners"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    llc_id = Column(String, nullable=False, index=True)
    name = Column(String, nullable=False)
    email = Column(String, nullable=False)
    ownership_percentage = Column(Float, nullable=False)
    join_date = Column(DateTime, nullable=False)
    tax_id = Column(String)
    phone = Column(String)
    address = Column(String)
    created_by = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    is_deleted = Column(Boolean, default=False)

class OwnerCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=200)
    email: EmailStr
    ownership_percentage: float = Field(..., ge=0, le=100)
    join_date: datetime
    tax_id: Optional[str] = None
    phone: Optional[str] = None
    address: Optional[str] = None

class OwnerUpdate(BaseModel):
    name: Optional[str] = None
    email: Optional[EmailStr] = None
    ownership_percentage: Optional[float] = Field(None, ge=0, le=100)
    tax_id: Optional[str] = None
    phone: Optional[str] = None
    address: Optional[str] = None

class OwnerResponse(BaseModel):
    id: str
    llc_id: str
    name: str
    email: str
    ownership_percentage: float
    join_date: datetime
    tax_id: Optional[str]
    phone: Optional[str]
    address: Optional[str]
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

owners_app = FastAPI(title="Owners Service", version="1.0.0")

@owners_app.post("/owners", response_model=OwnerResponse, status_code=status.HTTP_201_CREATED)
def create_owner(
    owner: OwnerCreate,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Create a new owner"""
    # Validate total ownership doesn't exceed 100%
    total_ownership = db.query(
        db.func.sum(OwnerDB.ownership_percentage)
    ).filter(
        OwnerDB.llc_id == token_data["llc_id"],
        OwnerDB.is_deleted == False
    ).scalar() or 0
    
    if total_ownership + owner.ownership_percentage > 100:
        raise HTTPException(
            status_code=400,
            detail=f"Total ownership would exceed 100% (current: {total_ownership}%)"
        )
    
    db_owner = OwnerDB(
        llc_id=token_data["llc_id"],
        created_by=token_data["user_id"],
        **owner.dict()
    )
    db.add(db_owner)
    db.commit()
    db.refresh(db_owner)
    return db_owner

@owners_app.get("/owners", response_model=List[OwnerResponse])
def get_owners(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Get all owners for the LLC"""
    return db.query(OwnerDB).filter(
        OwnerDB.llc_id == token_data["llc_id"],
        OwnerDB.is_deleted == False
    ).offset(skip).limit(limit).all()

@owners_app.get("/owners/{owner_id}", response_model=OwnerResponse)
def get_owner(
    owner_id: str,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Get a specific owner by ID"""
    owner = db.query(OwnerDB).filter(
        OwnerDB.id == owner_id,
        OwnerDB.llc_id == token_data["llc_id"],
        OwnerDB.is_deleted == False
    ).first()
    if not owner:
        raise HTTPException(status_code=404, detail="Owner not found")
    return owner

@owners_app.put("/owners/{owner_id}", response_model=OwnerResponse)
def update_owner(
    owner_id: str,
    owner_update: OwnerUpdate,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Update an owner"""
    db_owner = db.query(OwnerDB).filter(
        OwnerDB.id == owner_id,
        OwnerDB.llc_id == token_data["llc_id"],
        OwnerDB.is_deleted == False
    ).first()
    if not db_owner:
        raise HTTPException(status_code=404, detail="Owner not found")
    
    # Validate ownership percentage if being updated
    if owner_update.ownership_percentage is not None:
        total_ownership = db.query(
            db.func.sum(OwnerDB.ownership_percentage)
        ).filter(
            OwnerDB.llc_id == token_data["llc_id"],
            OwnerDB.id != owner_id,
            OwnerDB.is_deleted == False
        ).scalar() or 0
        
        if total_ownership + owner_update.ownership_percentage > 100:
            raise HTTPException(
                status_code=400,
                detail=f"Total ownership would exceed 100%"
            )
    
    update_data = owner_update.dict(exclude_unset=True)
    for key, value in update_data.items():
        setattr(db_owner, key, value)
    
    db.commit()
    db.refresh(db_owner)
    return db_owner

@owners_app.delete("/owners/{owner_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_owner(
    owner_id: str,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Soft delete an owner"""
    db_owner = db.query(OwnerDB).filter(
        OwnerDB.id == owner_id,
        OwnerDB.llc_id == token_data["llc_id"],
        OwnerDB.is_deleted == False
    ).first()
    if not db_owner:
        raise HTTPException(status_code=404, detail="Owner not found")
    
    db_owner.is_deleted = True
    db.commit()
    return None


# ==============================================================================
# 4. EXPENSES MICROSERVICE
# ==============================================================================

class ExpenseDB(Base):
    __tablename__ = "expenses"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    llc_id = Column(String, nullable=False, index=True)
    amount = Column(Float, nullable=False)
    category = Column(String, nullable=False)
    date = Column(DateTime, nullable=False)
    vendor = Column(String, nullable=False)
    description = Column(String)
    receipt_url = Column(String)
    tax_deductible = Column(Boolean, default=True)
    payment_method = Column(String)
    created_by = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    is_deleted = Column(Boolean, default=False)

class ExpenseCreate(BaseModel):
    amount: float = Field(..., gt=0)
    category: str = Field(..., examples=["Office Supplies", "Travel", "Marketing"])
    date: datetime
    vendor: str = Field(..., min_length=1, max_length=200)
    description: Optional[str] = None
    receipt_url: Optional[str] = None
    tax_deductible: bool = True
    payment_method: Optional[str] = Field(None, examples=["Credit Card", "Check", "Cash"])

class ExpenseUpdate(BaseModel):
    amount: Optional[float] = Field(None, gt=0)
    category: Optional[str] = None
    date: Optional[datetime] = None
    vendor: Optional[str] = None
    description: Optional[str] = None
    receipt_url: Optional[str] = None
    tax_deductible: Optional[bool] = None
    payment_method: Optional[str] = None

class ExpenseResponse(BaseModel):
    id: str
    llc_id: str
    amount: float
    category: str
    date: datetime
    vendor: str
    description: Optional[str]
    receipt_url: Optional[str]
    tax_deductible: bool
    payment_method: Optional[str]
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

expenses_app = FastAPI(title="Expenses Service", version="1.0.0")

@expenses_app.post("/expenses", response_model=ExpenseResponse, status_code=status.HTTP_201_CREATED)
def create_expense(
    expense: ExpenseCreate,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Create a new expense"""
    db_expense = ExpenseDB(
        llc_id=token_data["llc_id"],
        created_by=token_data["user_id"],
        **expense.dict()
    )
    db.add(db_expense)
    db.commit()
    db.refresh(db_expense)
    return db_expense

@expenses_app.get("/expenses", response_model=List[ExpenseResponse])
def get_expenses(
    skip: int = 0,
    limit: int = 100,
    category: Optional[str] = None,
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Get all expenses for the LLC with optional filters"""
    query = db.query(ExpenseDB).filter(
        ExpenseDB.llc_id == token_data["llc_id"],
        ExpenseDB.is_deleted == False
    )
    if category:
        query = query.filter(ExpenseDB.category == category)
    if start_date:
        query = query.filter(ExpenseDB.date >= start_date)
    if end_date:
        query = query.filter(ExpenseDB.date <= end_date)
    
    return query.order_by(ExpenseDB.date.desc()).offset(skip).limit(limit).all()

@expenses_app.get("/expenses/{expense_id}", response_model=ExpenseResponse)
def get_expense(
    expense_id: str,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Get a specific expense by ID"""
    expense = db.query(ExpenseDB).filter(
        ExpenseDB.id == expense_id,
        ExpenseDB.llc_id == token_data["llc_id"],
        ExpenseDB.is_deleted == False
    ).first()
    if not expense:
        raise HTTPException(status_code=404, detail="Expense not found")
    return expense

@expenses_app.put("/expenses/{expense_id}", response_model=ExpenseResponse)
def update_expense(
    expense_id: str,
    expense_update: ExpenseUpdate,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Update an expense"""
    db_expense = db.query(ExpenseDB).filter(
        ExpenseDB.id == expense_id,
        ExpenseDB.llc_id == token_data["llc_id"],
        ExpenseDB.is_deleted == False
    ).first()
    if not db_expense:
        raise HTTPException(status_code=404, detail="Expense not found")
    
    update_data = expense_update.dict(exclude_unset=True)
    for key, value in update_data.items():
        setattr(db_expense, key, value)
    
    db.commit()
    db.refresh(db_expense)
    return db_expense

@expenses_app.delete("/expenses/{expense_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_expense(
    expense_id: str,
    db: Session = Depends(get_db),
    token_data: dict = Depends(verify_token)
):
    """Soft delete an expense"""
    db_expense = db.query(ExpenseDB).filter(
        ExpenseDB.id == expense_id,
        ExpenseDB.llc_id == token_data["llc_id"],
        ExpenseDB.is_deleted == False
    ).first()
    if not db_expense:
        raise HTTPException(status_code=404, detail="Expense not found")
    
    db_expense.is_deleted = True
    db.commit()
    return None


